atelier:
    resource: "@AtelierBundle/Resources/config/routing.yml"
    prefix:   /

events:
    resource: "@EventsBundle/Resources/config/routing.yml"
    prefix:   /

event:
    resource: "@EventBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

reclamation:
    resource: "@ReclamationBundle/Resources/config/routing.yml"

forum:
    resource: "@ForumBundle/Resources/config/routing.yml"

actualite:
    resource: "@ActualiteBundle/Resources/config/routing.yml"

gererenfant:
    resource: "@GererEnfantBundle/Resources/config/routing.yml"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fullcalendar_load_events:
    path:     /fc-load-events
    defaults:
        _controller: AtelierBundle:Default:load

