gerer_enfant_homepage:
    path:     /
    defaults: { _controller: GererEnfantBundle:Default:index }

ajoutEnfant:
    path:     /ajoutEnfant
    defaults: { _controller: GererEnfantBundle:Enfant:ajoutEnfant }

message:
    path:     /message
    defaults: { _controller: GererEnfantBundle:Enfant:message }

afficheEnfantBack:
    path:     /afficheEnfantBack
    defaults: { _controller: GererEnfantBundle:Enfant:afficheEnfantBack }

updateEnfant:
    path:     /updateEnfant/{id}
    defaults: { _controller: GererEnfantBundle:Enfant:updateEnfant }

deleteEnfant:
    path:     /deleteEnfant/{id}
    defaults: { _controller: GererEnfantBundle:Enfant:deleteEnfant }

ajoutNote:
    path:     /ajoutNote/{id}
    defaults: { _controller: GererEnfantBundle:Note:ajoutNote}

afficheNote:
    path:     /afficheNote
    defaults: { _controller: GererEnfantBundle:Note:afficheNote }

updateNote:
    path:     /updateNote/{id}
    defaults: { _controller: GererEnfantBundle:Note:updateNote }

deleteNote:
    path:     /deleteNote/{id}
    defaults: { _controller: GererEnfantBundle:Note:deleteNote }