<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

<<<<<<< HEAD
if (\class_exists(\ContainerTj8ita1\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTj8ita1/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerTj8ita1.legacy');
=======
if (\class_exists(\ContainerXxunh4n\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXxunh4n/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXxunh4n.legacy');
>>>>>>> c4137eb80b33a1e2a5656fab05193e8b51bfbc64

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
<<<<<<< HEAD
    \class_alias(\ContainerTj8ita1\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerTj8ita1\appDevDebugProjectContainer([
    'container.build_hash' => 'Tj8ita1',
    'container.build_id' => '73c5de66',
    'container.build_time' => 1582043710,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTj8ita1');
=======
    \class_alias(\ContainerXxunh4n\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerXxunh4n\appDevDebugProjectContainer([
    'container.build_hash' => 'Xxunh4n',
    'container.build_id' => 'c58ca656',
    'container.build_time' => 1582042759,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXxunh4n');
>>>>>>> c4137eb80b33a1e2a5656fab05193e8b51bfbc64
