<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXxunh4n\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXxunh4n/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXxunh4n.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXxunh4n\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerXxunh4n\appDevDebugProjectContainer([
    'container.build_hash' => 'Xxunh4n',
    'container.build_id' => 'c58ca656',
    'container.build_time' => 1582042759,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXxunh4n');
