<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHlpndo5\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHlpndo5/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerHlpndo5.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerHlpndo5\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerHlpndo5\appDevDebugProjectContainer([
    'container.build_hash' => 'Hlpndo5',
    'container.build_id' => '49a9c225',
    'container.build_time' => 1582037224,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHlpndo5');
